services:

  database:
    image: mariadb
    container_name: tut-mariadb
    restart: always
    environment: # 환경변수
      MARIADB_ROOT_PASSWORD: tut1234
      MARIADB_USER: tut
      MARIADB_PASSWORD: tut1234
      MARIADB_DATABASE: ticket
      TZ: Asia/Seoul
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 6033:3306 # 3306
