services:

  database:
    image: mariadb
    container_name: tut-mariadb
    restart: always
    environment: # 환경변수
      TZ: Asia/Seoul
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - 6033:3306 # 3306
