global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "spark" # spark와 prometheus를 연결
    metrics_path: "/metrics/master/prometheus"
    static_configs:
      - targets: ["spark-master:8080"]

  - job_name: 'spark-driver'
    metrics_path: '/metrics/prometheus/'
    static_configs:
      - targets: ['spark-submit:4040']

